# Generated by Django 5.2.12 on 2026-03-26 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.CharField(primary_key=True, serialize=False)),
                ('category_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='login_info',
            fields=[
                ('empid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('emppassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='purchaseorder',
            fields=[
                ('purchase_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('purchase_item_name', models.CharField()),
                ('purchase_quantity', models.IntegerField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_shipment_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='salesorder',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('sales_quantity', models.IntegerField()),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipment_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
