# Generated by Django 5.2.12 on 2026-03-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_category_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_info',
            name='empname',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login_info',
            name='empid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
