# Generated by Django 5.2.10 on 2026-03-28 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_login_info_empname_alter_login_info_empid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_info',
            old_name='empname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='login_info',
            old_name='emppassword',
            new_name='position',
        ),
        migrations.AddField(
            model_name='login_info',
            name='contact',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='login_info',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='login_info',
            name='hired_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='login_info',
            name='password',
            field=models.CharField(default='changeme', max_length=128),
        ),
        migrations.AddField(
            model_name='login_info',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='login_info',
            name='sex',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
