# Generated by Django 5.2.10 on 2026-03-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_empname_login_info_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_id', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
