# Generated by Django 5.2.12 on 2026-03-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='membership',
            fields=[
                ('member_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
