# Generated by Django 5.2.12 on 2026-03-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_membership_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='contactnumber',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='dateofbirth',
            field=models.DateField(null=True, blank=True),
            preserve_default=False,
        ),
    ]
