# Generated by Django 5.2.12 on 2026-03-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_membership_contactnumber_membership_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='contactnumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
