# Generated by Django 5.2.12 on 2026-03-31 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_membership_date_alter_membership_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='dateofbirth',
            new_name='birthday',
        ),
    ]
