# Generated by Django 5.2.12 on 2026-03-31 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_dateofbirth_membership_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='birthday',
        ),
    ]
