# Generated by Django 5.2.10 on 2026-04-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_membership_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_date', models.DateField()),
                ('expense_description', models.CharField(max_length=255)),
                ('expense_category', models.CharField(max_length=255)),
            ],
        ),
    ]
