# Generated by Django 5.2.10 on 2026-04-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='expense_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
