# Generated by Django 5.2.12 on 2026-04-05 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_expenses_expense_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='restockorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restock_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('restock_quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('restock_date', models.DateField()),
                ('employee', models.ForeignKey(db_column='empid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.login_info')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
