# Generated by Django 5.2.12 on 2026-04-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_restockorder'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restockorder',
            table='restock_order',
        ),
    ]
