# Generated by Django 5.2.10 on 2026-04-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_restockorder_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restockorder',
            table=None,
        ),
    ]
