# Generated by Django 5.2.12 on 2026-04-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_purchaseorder_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_info',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
